version: '2'

services:
    web:
        build: web
        ports:
            - "80:80"
        restart: always
        networks:
            - main
        volumes:
            - ./web/app:/var/www
        # volume_driver: nfs
    mysql:
        build: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "drupal8"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        ports:
            - "3306:3306"
        restart: always
        networks:
            - main

networks:
    main:
        driver: bridge
